apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-pod-deployment
spec:
  selector:
    matchLabels:
      app: mongo
  replicas: 2
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: api-v1
        image: mongo
        ports:
        - containerPort: 27017
---
apiVersion: apps/v1
kind: Service
apiVersion: v1
metadata:
  name: mongo-pod
spec: 
  selector:
    app: mongo
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
    nodePort: 32000
  type: NodePort