apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  selector:
    matchLabels:
      app: node
  replicas: 2
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: api-v1
        image: api-node:v3
        env:
          - name: GREETING
            value: "Hello"
          - name: DATABASE
            value: mongo-pod
        ports:
        - containerPort: 3000
        imagePullPolicy: Never
        
---
apiVersion: apps/v1
kind: Service
apiVersion: v1
metadata:
  name: api-service
spec: 
  selector:
    app: node
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 31000
  type: NodePort